baseurl = "http://powershellusergroups.org.s3-website-us-east-1.amazonaws.com/"
languageCode = "en-US"
title = "PowerShell User Groups"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Chris Hunt"
  description = "PowerShell User Groups"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[social]
  Github        = "username"
  Email         = "email@example.com"
  Twitter       = "username"
  LinkedIn      = "username"
  Stackoverflow = "username"

## Main Menu
[[menu.main]]
  name = "Northern Virginia, VA, US"
  identifier = "nova"
  url = "http://www.meetup.com/NoVA-PowerShell-User-Group/"
[[menu.main]]
  name = "Boston, MA, US"
  identifier = "boston"
  url = "http://www.meetup.com/Boston-PowerShell-User-Group/"
