baseurl = "https://example.com/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-US"
theme = "hugo-sustain"
title = "Chris Turner"
[[menu.main]]
identifier = "groups"
name = "groups"
url = "/groups/"
weight = 100
[params]
author = "Chris Turner"
avatar = "profile.png"
custom_css = []
custom_js = []
description = "Describe your website"
[permalinks]
post = "/:year/:month/:day/:slug"
[social]
Email = "email@example.com"
Github = "username"
LinkedIn = "username"
Stackoverflow = "username"
Twitter = "username"
